LexiconLMS/Models/Activity.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace LexiconLMS.Models
{
    public class Activityy
    {
        public int Id { get; set; }

        [DataType(DataType.Date)]
        public DateTime StartDate { get; set; }

        [DataType(DataType.Date)]
        public DateTime EndDate { get; set; }

        public String Description { get; set; }

        //fk
        public int ActivityTypeId { get; set; }
        public int ModuleId{ get; set; }

        //nav ref
        public ActivityType ActivityType{ get; set; }
        public Module Module { get; set; }
        public ICollection<ActivityDocument> Documents { get; set; }


    }
}

LexiconLMS/Models/ActivityType.cs
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace LexiconLMS.Models
{
    public class ActivityType
    {
        public int Id { get; set; }

        [Display(Name ="Activity Type")]
        public string Type { get; set; }

        //nav collection
        //public ICollection<Activityy> Activities { get; set; }

    }
}

LexiconLMS/ViewModels/ActivityViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using LexiconLMS.Models;

namespace LexiconLMS.ViewModels
{
    public class ActivityViewModel: IDateInterval, IParentDateInterval
    {

        [Required]
        [DataType(DataType.Date)]
        public DateTime ParentStartDate { get; set; }

        [Required]
        [DataType(DataType.Date)]
        public DateTime ParentEndDate { get; set; }

        public int Id { get; set; }

        [Required]
        public int ModuleId { get; set; }

        
        [Display(Name ="Module name")]
        public string ModuleName { get; set; }

        //[Required]
        //[Display(Name = "Activity name")]
        //public string Name { get; set; }

        public string Description { get; set; }

        [Required]
        [Display(Name = "Start date")]
        [DataType(DataType.Date)]
        [StartDateNotEarlierThanParentStartDate(ErrorMessage = "Activity Start Date {0} must be later or equal to Module Start Date {1}")]
        public DateTime StartDate { get; set; }

        [Required]
        [Display(Name = "End date")]
        [DataType(DataType.Date)]
        [EndDateLaterThanStartDate]
        [EndDateNotLaterThanParentEndDate(ErrorMessage = "Activity End Date {0} must be earlier or equal to Module End Date {1}")]
        public DateTime EndDate { get; set; }

        //[Required]
        public ActivityType ActivityType { get; set; }

        public int ActivityTypeId { get; set; }

       

        //[Required]
        public Module Module { get; set; }
        public Course Course { get; set; }


    }
}

LexiconLMS/Controllers/ModuleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LexiconLMS.Data;
using LexiconLMS.Models;
using Microsoft.AspNetCore.Authorization;
using LexiconLMS.ViewModels;
using AutoMapper;
using Humanizer;

namespace LexiconLMS.Controllers
{
    [Authorize(Roles = "Teacher")]
    public class ModuleController : Controller
    {
        private readonly LexiconLMSContext _context;
        private readonly IMapper _mapper;

        public ModuleController(LexiconLMSContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }

       

        // GET: Module/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var module = await _context.Modules.FirstOrDefaultAsync(a => a.Id == id);

            if (module is null)
            {
                return NotFound();
            }

            var course = await _context.Courses.FirstOrDefaultAsync(a => a.Id == module.CourseId);

            if (course is null)
            {
                return NotFound();
            }

            //var model = _mapper.Map<ModuleDetailsViewModel>(@module);

            var model = new ModuleDetailsViewModel()
            {
                CourseId = course.Id,
                CourseName = course.Name,
                Id = module.Id,
                Name = module.Name,
                Description = module.Description,
                StartDate = module.StartDate,
                EndDate = module.EndDate,
                ParentStartDate = course.StartDate,
                ParentEndDate = course.EndDate
            };
            model.CourseId = course.Id;
            model.CourseName = course.Name;



            model.Activities = new List<ActivityDetailsViewModel>();
            var activities = _context.Activities
                .Include(a=>a.Module)
                .Include(a=>a.ActivityType)
                .Where(a => a.ModuleId == id)
                .OrderBy(d => d.StartDate)
                .ThenBy(e => e.EndDate).ToList();
            activities.ForEach(a => model.Activities.Add(_mapper.Map<ActivityDetailsViewModel>(a)));

            model.Documents = new List<DocumentListViewModel>();
            var documents = _context.ModuleDocument.Where(d => d.ModuleId == id).ToList();
            foreach (var doc in documents)
            {
                var newDoc = _mapper.Map<DocumentListViewModel>(doc);
                newDoc.Filezise = (doc.DocumentData.Length).Bytes().Humanize("#.#");
                model.Documents.Add(newDoc);
            }

            return View(model);
        }

        // GET: Module/Create
        public async Task<IActionResult> Create(int id)
        {
            if(!ModelState.IsValid)
            {
                return NotFound();
            }
            var course = await _context.Courses.FirstOrDefaultAsync(a => a.Id == id);

            if (course is null)
            {
                return NotFound();
            }

            var model = _mapper.Map<ModuleAddViewModel>(new Module());
            model.CourseId = course.Id;
            model.CourseName = course.Name;
            model.ParentStartDate = course.StartDate;
            model.ParentEndDate = course.EndDate;

            var dateTimeNow = DateTime.Now;
            model.StartDate = dateTimeNow;
            model.EndDate = dateTimeNow.AddDays(7);

            return View(model);
        }

        // POST: Module/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name, Description, StartDate, EndDate, DocId, CourseId, ParentStartDate, ParentEndDate, CourseName")] ModuleAddViewModel @module)
        {
            if (ModelState.IsValid)
            {
                var model = _mapper.Map<Module>(@module);
                _context.Add(model);

                await _context.SaveChangesAsync();
                TempData["AlertMsg"] = "Module added";
                return RedirectToAction(nameof(Details), new { id = model.Id });
            }
            return View(@module);
        }


        // GET: Module/Delete
        public async Task<IActionResult> Delete(int id)
        {
            if (!ModelState.IsValid)
            {
                return NotFound();
            }

            var module = await _context.Modules.FirstOrDefaultAsync(a => a.Id == id);
            if (!(module is null))
            {
                _context.Remove(module);
                _context.SaveChanges();

                var course = await _context.Courses.FirstOrDefaultAsync(a => a.Id == module.CourseId);
                if (!(course is null))
                {
                    TempData["AlertMsg"] = "Module deleted";
                    return RedirectToAction("Details", "Course", new { id = course.Id });
                }
            }

            return NotFound();
        }


        // GET: Module/Edit
        public async Task<IActionResult> Edit(int id)
        {
            if (!ModelState.IsValid)
            {
                return NotFound();
            }

            var module = await _context.Modules.FirstOrDefaultAsync(a => a.Id == id);
            if (!(module is null))
            {
                var course = await _context.Courses.FirstOrDefaultAsync(a => a.Id == module.CourseId);
                if (!(course is null))
                {
                    var model = _mapper.Map<Module, ModuleAddViewModel>(module);
                    model.CourseId = course.Id;
                    model.CourseName = course.Name;
                    model.ParentStartDate = course.StartDate;
                    model.ParentEndDate = course.EndDate;
                    return View(model);
                }
            }

            return NotFound();
        }


        // POST: Module/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("Id, Name, Description, StartDate, EndDate, CourseId, ParentStartDate, ParentEndDate, CourseName")] ModuleAddViewModel @module)
        {
            if (ModelState.IsValid)
            {
                var moduleEntity = await _context.Modules.FirstOrDefaultAsync(a => a.Id == @module.Id);

                moduleEntity.Name = @module.Name;
                moduleEntity.StartDate = @module.StartDate;
                moduleEntity.EndDate = @module.EndDate;
                moduleEntity.Description = @module.Description;

                var activitiesOutSideStartEndDate = await GetActivitiesOutSideCourseStartEndDates(moduleEntity);
                if (activitiesOutSideStartEndDate.Count() > 0)
                {
                    var errorCount = 0;
                    foreach (var activity in activitiesOutSideStartEndDate)
                    {
                        ModelState.AddModelError($"activity_start_end_error_{errorCount++}", $"Activity: {activity.Description} {activity.StartDate.ToString(Common.DateFormat)} - {activity.EndDate.ToString(Common.DateFormat)} is outside module Start/End dates");
                    }
                    return View(@module);
                }

                _context.Update(moduleEntity);
                await _context.SaveChangesAsync();

                TempData["AlertMsg"] = "Saved changes";
                return RedirectToAction(nameof(Details), new { id = moduleEntity.Id });
            }

            return View(@module);
        }


        private async Task<List<Activityy>> GetActivitiesOutSideCourseStartEndDates(Module @module)
        {
            var res = new List<Activityy>();
            var activities = await _context.Activities.Where(a => a.ModuleId == @module.Id).ToListAsync();
            foreach (var activity in activities)
            {
                if (@module.StartDate.CompareTo(activity.StartDate) > 0 || @module.EndDate.CompareTo(activity.EndDate) < 0)
                {
                    res.Add(activity);
                }
            }
            return res;
        }
    }
}

LexiconLMS/Views/Activity/Create.cshtml
@model LexiconLMS.ViewModels.ActivityAddViewModel
@{
    ViewData["Title"] = "Create Activity";
}

<div>
    <partial name="_ActivityBreadCrumbPartial" />
</div>
<hr />
<h5>Create Activity:</h5>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="All" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="ActivityTypeId" class="control-label"></label>
                <select asp-for="ActivityTypeId" class="form-control" asp-items="ViewBag.ActivityTypeId"></select>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>


                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <textarea asp-for="Description" class="form-control"></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>

            </div>

            <input type="hidden" asp-for="ModuleId" class="form-control" />
            <input type="hidden" asp-for="ModuleName" class="form-control" />
            <input type="hidden" asp-for="ParentStartDate" class="form-control" />
            <input type="hidden" asp-for="ParentEndDate" class="form-control" />

            <div>
                <input type="submit" value="Save" class="btn btn-green" />
                <a asp-action="Details" asp-controller="Module" class="btn btn-grey" asp-route-id="@Model.ModuleId"></i>Cancel</a>

            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LexiconLMS/Views/Activity/Details.cshtml
@model LexiconLMS.ViewModels.ActivityDetailsViewModel

@{
    ViewData["Title"] = "Details";
}

<div>
    <partial name="_ActivityBreadCrumbPartialDetails" />
</div>
<hr />
<h5>Activity Details:</h5>

<div>
    <dl class="row">
        <dd class="col-sm-1"></dd>
        <dd class="col-sm-8">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dd class="col-sm-3"></dd>
        <dd class="col-sm-1"></dd>
        <dt class="col-sm-8">
            <i class="fa fa-clock"></i>@Html.DisplayNameFor(model => model.StartDate) <strong>@Model.StartDate.ToLongDateString()</strong>
        </dt>
        <dd class="col-sm-3"></dd>
        <dd class="col-sm-1"></dd>
        <dt class="col-sm-8">
            <i class="fa fa-clock"></i>@Html.DisplayNameFor(model => model.EndDate) <strong>@Model.EndDate.ToLongDateString()</strong>
        </dt>
        <dd class="col-sm-3"></dd>

    </dl>
</div>

<hr />
<div>
    <a asp-action="Create" asp-controller="ActivityDocument" asp-route-id="@Model.Id" class="btn btn-sm btn-secondary"><i class="fas fa-file-upload"></i> Add Document</a>
</div>
<table class="table tablestyle" data-toggle="table">
    <tbody>
        @foreach (var document in Model.Documents)
        {
            <tr>
                <td><i class="fas fa-file-download"></i> @Html.ActionLink(document.Name, "Display", "ActivityDocument", new { id = document.Id }) (@document.Filezise)</td>
                <td><i class="fas fa-clock"></i> @Html.DisplayFor(d => document.UploadTime)</td>
                <td><i class="fas fa-info-circle"></i> @document.Description</td>

                <td>
                    <div class="btn btn-grey btn-sm">
                        <a href="@Url.Action("Delete", "ActivityDocument", new { id = document.Id })" class="text-white"><i class="fa fa-trash" aria-hidden="true"></i>Remove</a>
                    </div>

                </td>
            </tr>
        }
    </tbody>
</table>
<div>
    <a asp-controller="Module" asp-action="Details" asp-route-id="@Model.ModuleId" class="btn btn-purple">Back to Module</a>
    <a asp-action="Index" class="btn btn-green">All Activities</a>
</div>

LexiconLMS/Views/Activity/Edit.cshtml
@model LexiconLMS.ViewModels.ActivityAddViewModel

@{
    ViewData["Title"] = "Edit";
}

<div>
    <partial name="_ActivityBreadCrumbPartial" />
</div>
<hr />
<h5>Edit Activity:</h5>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="All" class="text-danger"></div>



            <div class="form-group">
                <label asp-for="ActivityTypeId" class="control-label"></label>
                <select asp-for="ActivityTypeId" class="form-control" asp-items="ViewBag.ActivityTypeId"></select>
                <span asp-validation-for="ActivityTypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="ParentStartDate" class="form-control" />
            <input type="hidden" asp-for="ParentEndDate" class="form-control" />

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-green" />
                <a asp-action="Details" asp-controller="Module" asp-route-Id="@Model.Module.Id" class="btn btn-purple">Back To Module</a>
                <a asp-action="Index" class="btn btn-grey">Back To List</a>
            </div>
        </form>
    </div>
</div>

LexiconLMS/Views/Activity/Index.cshtml
@model IEnumerable<LexiconLMS.Models.Activityy>

@{
    ViewData["Title"] = "Index";
}

<h1>Activities</h1>

@*<p>
        <a asp-action="Create">Create New</a>
    </p>*@
<table class="table widetablestyle">
    <thead>
        <tr>

            <th>
                @Html.DisplayNameFor(model => model.ActivityType)
            </th>
            <th colspan="2" >
                @Html.DisplayNameFor(model => model.Module.Course)
            </th>
            <th colspan="2">
                @Html.DisplayNameFor(model => model.Module)
            </th>
            <th colspan="2" >
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndDate)
            </th>




            <th></th>
          
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.ActivityType.Type)
            </td>
            <td colspan="2">
                @Html.DisplayFor(modelItem => item.Module.Course.Name)
            </td>
            <td colspan="2">
                @Html.DisplayFor(modelItem => item.Module.Name)
            </td>
            <td colspan="2">
                <i class="fa  fa-info-circle"></i> @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                <i class="fa fa-clock" aria-hidden="true"></i> @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td>
                <i class="fa fa-clock" aria-hidden="true"></i> @Html.DisplayFor(modelItem => item.EndDate)
            </td>





            <td>
                <div class="btn btn-purple btn-sm"><i class="fa fa-edit"></i> @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "text-white" })</div>
                @*</td>

            <td>*@
                <div class="btn btn-green btn-sm"><i class="fa fa-info-circle"></i> @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "text-white" })</div>
                @*@Html.ActionLink("Delete", "Delete", new { id = item.Id })*@
            </td>

        </tr>
        }
    </tbody>
</table>

@*<hr />

<hr />*@
<div>
    
    <a asp-action="Index" asp-controller="Teacher" class="btn btn-purple">Back to Home</a>
</div>